name: Production

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  docker:
    name: Build & Deploy Docker
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
    - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/wg-easy/wg-easy
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}
            type=semver,pattern={{major}}.{{minor}}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build & Publish Docker Image
      uses: docker/build-push-action@v6
      with:
        push: true
        platforms: linux/amd64
        tags: ghcr.io/f97/wg-easy:latest, ghcr.io/f97/wg-easy:${{ env.RELEASE }}
